name: Deploy # name of the action (displayed in the github interface)

on: # event list
  push: # on a merge event to each of these branches
    branches:
      - main

jobs: # list of things to do
  deploying:
    name: Deploying # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Code Build and Deploy
        run: npm run deploy-service-prod
